@LAZYGLOBAL OFF.

//TODO:
//DECLARE LOCAL FUNCTION MMULT {
//    DECLARE LOCAL PARAMETER R1, R2, R3, X.
//    RETURN V(VDOT(R1, X), VDOT(R2, X), VDOT(R3, X)).
//}

//DECLARE LOCAL FUNCTION FIXEDFRAME {
//    PARAMETER B IS BODY.
//    DECLARE LOCAL E IS LEXICON().
//}

//TODO:
//DECLARE LOCAL FUNCTION ORBITFRAME {
//    PARAMETER OBT IS ORBIT.
//    DECLARE LOCAL O IS LEXICON().
//}

//TODO:
//DECLARE LOCAL FUNCTION ORBITVELOCITYFRAME {
//    PARAMETER OBT IS ORBIT.
//    DECLARE LOCAL V IS LEXICON().
//}

DECLARE LOCAL LIB IS LIST().
RUNPATH("/L/USE.KS",LIB).
DECLARE GLOBAL USE IS LIB[0].

DECLARE LOCAL INERTIALFRAME IS USE("/L/INERTIALFRAME.KS").
DECLARE LOCAL PERIFOCALFRAME IS USE("/L/PERIFOCALFRAME.KS").
DECLARE LOCAL VL2R IS USE("/L/VL2R.KS").
DECLARE LOCAL XFORMCOORD IS USE("/L/XFORMCOORD.KS").

CLEARVECDRAWS().

DECLARE LOCAL V0 IS V(0,0,0).

DECLARE LOCAL SCALE IS 1.
DECLARE LOCAL WIDTH IS 1.

DECLARE LOCAL SLEN IS 200000.
DECLARE LOCAL NLEN IS 2 * BODY:RADIUS.

DECLARE LOCAL SIVEC IS VECDRAW(V0, SLEN * V(1, 0, 0), RED, "", SCALE, TRUE, WIDTH).
DECLARE LOCAL SJVEC IS VECDRAW(V0, SLEN * V(0, 0, 1), GREEN, "", SCALE, TRUE, WIDTH).
DECLARE LOCAL SKVEC IS VECDRAW(V0, SLEN * V(0, 1, 0), BLUE, "", SCALE, TRUE, WIDTH).

DECLARE LOCAL NIVEC IS VECDRAW(V0, V0, RED, "", SCALE, TRUE, WIDTH).
DECLARE LOCAL NJVEC IS VECDRAW(V0, V0, GREEN, "", SCALE, TRUE, WIDTH).
DECLARE LOCAL NKVEC IS VECDRAW(V0, V0, BLUE, "", SCALE, TRUE, WIDTH).

DECLARE LOCAL PIVEC IS VECDRAW(V0, V0, RED, "", SCALE, TRUE, WIDTH).
DECLARE LOCAL PJVEC IS VECDRAW(V0, V0, GREEN, "", SCALE, TRUE, WIDTH).
DECLARE LOCAL PKVEC IS VECDRAW(V0, V0, BLUE, "", SCALE, TRUE, WIDTH).

DECLARE LOCAL RVEC IS VECDRAW(V0, V0, YELLOW, "", SCALE, TRUE, WIDTH).
// DECLARE LOCAL VVEC IS VECDRAW(V0, V0, MAGENTA, "V", SCALE, TRUE, WIDTH).

UNTIL 0 {
    DECLARE LOCAL N IS INERTIALFRAME().

    SET RVEC:START TO BODY:POSITION.
    SET RVEC:VEC TO 1000000 * SOLARPRIMEVECTOR.

    SET NIVEC:START TO BODY:POSITION.
    SET NJVEC:START TO BODY:POSITION.
    SET NKVEC:START TO BODY:POSITION.

    SET NIVEC:VEC TO NLEN * VL2R(N:I).
    SET NJVEC:VEC TO NLEN * VL2R(N:J).
    SET NKVEC:VEC TO NLEN * VL2R(N:K).

    IF HASTARGET {
        DECLARE LOCAL P IS PERIFOCALFRAME(TARGET:OBT).
        DECLARE LOCAL PLEN IS TARGET:OBT:PERIAPSIS + TARGET:BODY:RADIUS.

        SET PIVEC:START TO BODY:POSITION.
        SET PJVEC:START TO BODY:POSITION.
        SET PKVEC:START TO BODY:POSITION.

        SET PIVEC:VEC TO VL2R(XFORMCOORD(N, PLEN * P:I)).
        SET PJVEC:VEC TO VL2R(XFORMCOORD(N, PLEN * P:J)).
        SET PKVEC:VEC TO VL2R(XFORMCOORD(N, PLEN * P:K)).
    }

    WAIT 1.
}
