@LAZYGLOBAL OFF.
DECLARE PARAMETER F IS 0.
PRINT"$ INIT.KS".
IF NOT EXISTS("/L/USE.KS")COPYPATH("0:L/USE.KS","/L/USE.KS").
DECLARE LOCAL LIB IS LIST().
RUNPATH("/L/USE.KS",LIB).
DECLARE GLOBAL USE IS LIB[0].
USE("/L/MAIN.KS")(F).
